const cards = [
    {
        name: "Fool",
        words: [
            "beginning",
            "carelessness",
            "ignorance",
            "inexperience",
            "innocence",
            "new choice",
            "potential",
            "spontaneity",
        ],
    },
    {
        name: "Magician",
        words: [
            "ability",
            "action",
            "concentration",
            "confidence",
            "conscious mind",
            "control",
            "power",
            "skill",
            "talent",
            "yang",
        ],
    },
    {
        name: "High Priestess",
        words: [
            "intuition",
            "meditation",
            "mystery",
            "passivity",
            "potential",
            "secret",
            "spiritual connection",
            "unconscious mind",
            "yin",
        ],
    },
    {
        name: "Empress",
        words: [
            "abundance",
            "beauty",
            "creativity",
            "desire",
            "femininity",
            "material world",
            "maternity",
            "nature",
            "pleasure",
            "protection",
        ],
    },
    {
        name: "Emperor",
        words: [
            "authority",
            "experience",
            "hierarchy",
            "masculinity",
            "paternity",
            "power",
            "rationality",
            "regulation",
            "responsibility",
            "rule",
            "structure",
        ],
    },
    {
        name: "Hierophant",
        words: [
            "belief",
            "conformity",
            "education",
            "faith",
            "group",
            "guidance",
            "hierarchy",
            "initiation",
            "institution",
            "ritual",
            "spiritual connection",
            "tradition",
        ],
    },
    {
        name: "Lovers",
        words: [
            "choice",
            "desire",
            "harmony",
            "intimacy",
            "love",
            "passion",
            "pleasure",
            "relationship",
            "self-confidence",
            "sex",
            "union",
        ],
    },
    {
        name: "Chariot",
        words: [
            "assertion",
            "bravery",
            "control",
            "determination",
            "emotional discipline",
            "movement",
            "physical conquest",
            "travel",
            "victory",
            "willpower",
        ],
    },
    {
        name: "Strength",
        words: [
            "bravery",
            "composure",
            "confidence",
            "courage",
            "determination",
            "endurance",
            "energy",
            "fortitude of character",
            "health",
            "nonphysical conquest",
            "patience",
            "strength",
        ],
    },
    {
        name: "Hermit",
        words: [
            "contemplation",
            "enlightenment",
            "guidance",
            "introspection",
            "meditation",
            "search",
            "self-sufficiency",
            "solitude",
        ],
    },
    {
        name: "Wheel of Fortune",
        words: [
            "cycle",
            "destiny",
            "luck",
            "movement",
            "potential",
            "turning point",
            "unstoppable change",
            "vision",
        ],
    },
    {
        name: "Justice",
        words: [
            "balance",
            "cause-and-effect",
            "decision",
            "fairness",
            "justice",
            "rationality",
            "responsibility",
            "rule",
            "truth",
        ],
    },
    {
        name: "Hanged Man",
        words: [
            "acceptance",
            "altered perspective",
            "meditation",
            "punishment",
            "release",
            "restriction",
            "sacrifice",
            "suspense",
            "upside-down",
            "wait",
        ],
    },
    {
        name: "Death",
        words: [
            "dramatic transformation",
            "elimination",
            "ending",
            "lifestyle change",
            "loss",
            "release",
            "transition",
            "turning point",
            "unstoppable change",
        ],
    },
    {
        name: "Temperance",
        words: [
            "adaptation",
            "balance",
            "combination",
            "compromise",
            "cooperation",
            "health",
            "moderation",
            "patience",
        ],
    },
    {
        name: "Devil",
        words: [
            "bondage",
            "deception",
            "hedonism",
            "hopelessness",
            "ignorance",
            "loss of control",
            "loss of faith",
            "materialism",
            "selfishness",
            "temptation",
            "weakness",
        ],
    },
    {
        name: "Tower",
        words: [
            "chaos",
            "disaster",
            "humbling experience",
            "punishment",
            "release",
            "revelation",
            "separation",
            "sudden change",
            "upheaval",
        ],
    },
    {
        name: "Star",
        words: [
            "beauty",
            "faith",
            "generosity",
            "guidance",
            "hope",
            "illumination",
            "inspiration",
            "peace",
            "renewal",
            "serenity",
        ],
    },
    {
        name: "Moon",
        words: [
            "confusion",
            "deception",
            "dream",
            "fear",
            "illusion",
            "imagination",
            "magnetism",
            "strangeness",
            "unconscious mind",
        ],
    },
    {
        name: "Sun",
        words: [
            "assurance",
            "bliss",
            "brightness",
            "energy",
            "enlightenment",
            "generosity",
            "greatness",
            "growth",
            "happiness",
            "illumination",
            "joy",
            "success",
            "vitality",
            "warmth",
        ],
    },
    {
        name: "Judgment",
        words: [
            "absolution",
            "cause-and-effect",
            "release",
            "revelation",
            "sense of purpose",
            "spiritual rebirth",
            "transformation",
        ],
    },
    {
        name: "World",
        words: [
            "accomplishment",
            "achievement",
            "completion",
            "ending",
            "enlightenment",
            "freedom",
            "fulfillment",
            "integration",
            "promotion",
        ],
    },
    {
        name: "Ace of Pentacles",
        words: [
            "abundance",
            "beginning",
            "creative urge",
            "fortune",
            "gain",
            "gift",
            "inspiration",
            "manifestation",
            "materialism",
            "opportunity",
            "physical world",
            "potential",
            "presence",
            "success",
        ],
    },
    {
        name: "2 of Pentacles",
        words: [
            "balance",
            "choice",
            "dance",
            "decision",
            "dexterity",
            "division",
            "duality",
            "flexibility",
            "force",
            "joy",
        ],
    },
    {
        name: "3 of Pentacles",
        words: [
            "art",
            "collaboration",
            "community",
            "concept",
            "consulting",
            "craft",
            "creativity",
            "flux",
            "inspiration",
            "installation",
            "outcome",
            "project",
            "skill",
            "talent",
            "teamwork",
            "trade",
            "work",
        ],
    },
    {
        name: "4 of Pentacles",
        words: [
            "concentration",
            "control",
            "determination",
            "expansion",
            "gain",
            "greed",
            "hardiness",
            "inheritance",
            "investment",
            "outcome",
            "possession",
            "possessiveness",
            "realization",
            "savings",
            "selfishness",
            "stability",
            "stagnation",
            "thrift",
        ],
    },
    {
        name: "5 of Pentacles",
        words: [
            "adversity",
            "challenge",
            "change",
            "cold",
            "darkness",
            "despair",
            "hardship",
            "insecurity",
            "lack",
            "loss",
            "need",
            "obstacle",
            "poverty",
            "rejection",
            "restriction",
            "sadness",
            "struggle",
            "victim",
            "waste",
            "yearning",
        ],
    },
    {
        name: "6 of Pentacles",
        words: [
            "altruism",
            "balance",
            "comfort",
            "distribution",
            "fairness",
            "gain",
            "generosity",
            "gift",
            "growth",
            "help",
            "illumination",
            "journey",
            "justice",
            "mercy",
            "offer",
            "success",
            "sympathy",
            "wealth",
        ],
    },
    {
        name: "7 of Pentacles",
        words: [
            "accomplishment",
            "bloom",
            "business",
            "challenge",
            "charity",
            "checking",
            "contemplation",
            "counting",
            "creativity",
            "deal",
            "development",
            "exchange",
            "expansion",
            "faith",
            "investment",
            "planning",
            "ripening",
            "willpower",
        ],
    },
    {
        name: "8 of Pentacles",
        words: [
            "autonomy",
            "change",
            "commitment",
            "craft",
            "dedication",
            "dexterity",
            "diligence",
            "finesse",
            "habit",
            "learning",
            "logic",
            "proficiency",
            "progress",
            "refinement",
            "repetitive",
            "routine",
            "skill",
            "strength",
            "technique",
        ],
    },
    {
        name: "9 of Pentacles",
        words: [
            "accomplishment",
            "discernment",
            "elegance",
            "fruition",
            "fulfillment",
            "gratitude",
            "independence",
            "investment",
            "joy",
            "potential",
            "project",
            "prudence",
            "refinement",
            "safety",
            "self-reliance",
            "transformation",
        ],
    },
    {
        name: "10 of Pentacles",
        words: [
            "completion",
            "culmination",
            "ending",
            "family",
            "home",
            "legacy",
            "manifestation",
            "materialism",
            "safety",
            "treasure",
            "wealth",
        ],
    },
    {
        name: "Page of Pentacles",
        words: [
            "apprenticeship",
            "certainty",
            "dependable",
            "health",
            "inspiration",
            "potential",
            "practicality",
            "presence",
            "stability",
        ],
    },
    {
        name: "Knight of Pentacles",
        words: [
            "action",
            "delusion",
            "determination",
            "efficiency",
            "formation",
            "irrationality",
            "irresponsibility",
            "materialism",
            "opportunity",
            "wealth",
        ],
    },
    {
        name: "Queen of Pentacles",
        words: [
            "capability",
            "care",
            "comfort",
            "concept",
            "conservation",
            "generosity",
            "influence",
            "maternity",
            "organization",
            "protection",
            "rationality",
            "satisfaction",
            "sensuality",
            "warmth",
            "wealth",
        ],
    },
    {
        name: "King of Pentacles",
        words: [
            "ambition",
            "authority",
            "business",
            "creative urge",
            "dependable",
            "discipline",
            "enterprise",
            "entrepreneur",
            "materialism",
            "rationality",
            "security",
            "stability",
            "success",
            "wealth",
        ],
    },
    {
        name: "Ace of Swords",
        words: [
            "accomplishment",
            "accountability",
            "anger",
            "beginning",
            "clarity",
            "creative urge",
            "determination",
            "potential",
            "responsibility",
            "retribution",
        ],
    },
    {
        name: "2 of Swords",
        words: [
            "adaptation",
            "adjustment",
            "balance",
            "blindness",
            "blockage",
            "choice",
            "compromise",
            "contemplation",
            "decision",
            "denial",
            "duality",
            "duel",
            "force",
            "grace",
            "meditation",
            "stalemate",
            "subtlety",
            "tension",
        ],
    },
    {
        name: "3 of Swords",
        words: [
            "betrayal",
            "community",
            "concept",
            "flux",
            "grief",
            "guilt",
            "heartbreak",
            "injury",
            "loneliness",
            "meditation",
            "outcome",
            "pain",
            "regret",
            "rejection",
            "sadness",
            "separation",
            "suffering",
            "treason",
        ],
    },
    {
        name: "4 of Swords",
        words: [
            "expansion",
            "outcome",
            "peace",
            "possession",
            "protection",
            "recuperation",
            "reflection",
            "rest",
            "retirement",
            "retreat",
            "sleep",
            "solitude",
            "stability",
            "truce",
            "wait",
        ],
    },
    {
        name: "5 of Swords",
        words: [
            "adversity",
            "challenge",
            "change",
            "conflict",
            "cowardice",
            "cruelty",
            "defeat",
            "degradation",
            "difficulty",
            "disgrace",
            "domination",
            "drama",
            "exile",
            "failure",
            "power",
            "restriction",
            "retribution",
            "sadness",
            "slander",
            "tension",
            "uncertainty",
            "unfairness",
            "weakness",
        ],
    },
    {
        name: "6 of Swords",
        words: [
            "balance",
            "curiosity",
            "exploration",
            "flux",
            "growth",
            "illumination",
            "journey",
            "movement",
            "obstacle",
            "reasoning",
            "recovery",
            "speed",
            "transfer",
            "transition",
            "travel",
        ],
    },
    {
        name: "7 of Swords",
        words: [
            "attempt",
            "betrayal",
            "challenge",
            "confidentiality",
            "creativity",
            "deception",
            "defeat",
            "faith",
            "gossip",
            "hidden",
            "loss",
            "plan",
            "secret",
            "stealth",
            "willpower",
        ],
    },
    {
        name: "8 of Swords",
        words: [
            "betrayal",
            "bondage",
            "censorship",
            "change",
            "entrapment",
            "isolation",
            "laziness",
            "logic",
            "obstacle",
            "progress",
            "restriction",
            "strength",
            "stunned",
        ],
    },
    {
        name: "9 of Swords",
        words: [
            "concern",
            "crisis",
            "deceit",
            "despair",
            "difficulty",
            "disappointment",
            "doubt",
            "fruition",
            "fulfillment",
            "guilt",
            "loss",
            "nightmare",
            "overwhelming",
            "potential",
            "regret",
            "sadness",
            "sleeplessness",
            "suffering",
            "transformation",
            "uncertainty",
            "worry",
        ],
    },
    {
        name: "10 of Swords",
        words: [
            "blockage",
            "completion",
            "crisis",
            "culmination",
            "defeat",
            "disaster",
            "ending",
            "failure",
            "fear",
            "manifestation",
            "obsession",
            "pain",
            "sacrifice",
            "sadness",
        ],
    },
    {
        name: "Page of Swords",
        words: [
            "aggression",
            "anger",
            "attention",
            "calculation",
            "dexterity",
            "energy",
            "vigilance",
        ],
    },
    {
        name: "Knight of Swords",
        words: [
            "action",
            "anger",
            "determination",
            "extreme",
            "formation",
            "haste",
            "hostility",
            "impatience",
            "impetuous",
            "movement",
            "opportunity",
            "power",
            "rebel",
            "temperament",
            "violence",
            "warrior",
        ],
    },
    {
        name: "Queen of Swords",
        words: [
            "concept",
            "decision",
            "directness",
            "discrimination",
            "honesty",
            "influence",
            "logic",
            "organization",
            "perception",
            "power",
            "pretension",
            "rigorous",
            "satisfaction",
            "strength",
        ],
    },
    {
        name: "King of Swords",
        words: [
            "analysis",
            "articulation",
            "authority",
            "calm",
            "creative urge",
            "diplomacy",
            "focus",
            "guidance",
            "impartiality",
            "intellect",
            "judgment",
            "justice",
            "logic",
            "order",
            "power",
            "precision",
            "rationality",
            "stability",
            "tact",
        ],
    },
    {
        name: "Ace of Cups",
        words: [
            "abundance",
            "adaptation",
            "beginning",
            "care",
            "compassion",
            "creative urge",
            "deluge",
            "emotion",
            "fertility",
            "intuition",
            "joy",
            "love",
            "memory",
            "openness",
            "opportunity",
            "potential",
            "purification",
            "romance",
            "unconscious mind",
        ],
    },
    {
        name: "2 of Cups",
        words: [
            "agreement",
            "attraction",
            "balance",
            "decision",
            "duality",
            "force",
            "friendship",
            "harmony",
            "joy",
            "love",
            "marriage",
            "partnership",
            "passion",
            "relationship",
            "sympathy",
            "understanding",
            "union",
        ],
    },
    {
        name: "3 of Cups",
        words: [
            "birth",
            "collaboration",
            "comfort",
            "communion",
            "community",
            "concept",
            "dance",
            "excitement",
            "feast",
            "flux",
            "friendship",
            "health",
            "intoxication",
            "joy",
            "outcome",
            "relief",
            "sharing",
            "teamwork",
            "victory",
            "work",
        ],
    },
    {
        name: "4 of Cups",
        words: [
            "boredom",
            "complacency",
            "contemplation",
            "disappointment",
            "discontent",
            "discouragement",
            "disdain",
            "dissatisfaction",
            "distraction",
            "expansion",
            "expectation",
            "habit",
            "nausea",
            "outcome",
            "possession",
            "refusal",
            "stability",
        ],
    },
    {
        name: "5 of Cups",
        words: [
            "addiction",
            "adversity",
            "bereavement",
            "change",
            "despair",
            "difficulty",
            "disappointment",
            "fear",
            "guilt",
            "pessimism",
            "refusal",
            "regret",
            "restriction",
            "sacrifice",
            "sadness",
            "shortage",
            "sorrow",
            "vanity",
        ],
    },
    {
        name: "6 of Cups",
        words: [
            "balance",
            "endowment",
            "exchange",
            "friendship",
            "gift",
            "growth",
            "hearth",
            "home",
            "illumination",
            "journey",
            "joy",
            "message",
            "nostalgia",
            "offer",
            "passion",
            "peace",
            "remembrance",
            "romance",
            "safety",
            "sentiment",
            "sharing",
            "yearning",
        ],
    },
    {
        name: "7 of Cups",
        words: [
            "challenge",
            "choice",
            "creativity",
            "deception",
            "desire",
            "dream",
            "faith",
            "fantasy",
            "illusion",
            "imagination",
            "indecision",
            "option",
            "selection",
            "temptation",
            "variety",
            "vision",
            "willpower",
        ],
    },
    {
        name: "8 of Cups",
        words: [
            "adventure",
            "change",
            "escapism",
            "freedom",
            "journey",
            "logic",
            "loneliness",
            "movement",
            "progress",
            "rejection",
            "renunciation",
            "restart",
            "shyness",
            "strength",
            "transition",
            "travel",
        ],
    },
    {
        name: "9 of Cups",
        words: [
            "admiration",
            "affection",
            "contentment",
            "fruition",
            "fulfillment",
            "pleasure",
            "potential",
            "satisfaction",
            "sensuality",
            "success",
            "transformation",
            "virtue",
            "yes",
        ],
    },
    {
        name: "10 of Cups",
        words: [
            "commitment",
            "community",
            "completion",
            "contentment",
            "culmination",
            "ending",
            "family",
            "friendship",
            "fulfillment",
            "happiness",
            "harmony",
            "joy",
            "manifestation",
            "peace",
            "rest",
            "success",
        ],
    },
    {
        name: "Page of Cups",
        words: [
            "contemplation",
            "devotion",
            "emotion",
            "enthusiasm",
            "friendship",
            "gentleness",
            "grace",
            "idea",
            "insight",
            "inspiration",
            "instinct",
            "intuition",
            "joy",
            "openness",
            "perception",
            "potential",
            "presence",
            "receptivity",
            "romance",
            "sweetness",
            "synchronicity",
        ],
    },
    {
        name: "Knight of Cups",
        words: [
            "action",
            "charm",
            "compassion",
            "determination",
            "emotion",
            "encouragement",
            "flattery",
            "formation",
            "idealism",
            "imagination",
            "insight",
            "introspection",
            "opportunity",
            "pleasure",
            "reflection",
            "seduction",
            "sensitivity",
            "temperament",
            "warmth",
        ],
    },
    {
        name: "Queen of Cups",
        words: [
            "affection",
            "attraction",
            "charm",
            "compassion",
            "concept",
            "emotion",
            "empathy",
            "friend",
            "influence",
            "intuition",
            "kindness",
            "listening",
            "love",
            "mystery",
            "reflection",
            "response",
            "satisfaction",
            "sensitivity",
            "support",
            "sweetness",
            "sympathy",
            "tranquility",
            "understanding",
            "warmth",
        ],
    },
    {
        name: "King of Cups",
        words: [
            "affection",
            "attraction",
            "authority",
            "charm",
            "chivalry",
            "compassion",
            "composure",
            "cooperation",
            "creative urge",
            "culture",
            "grace",
            "intuition",
            "joy",
            "love",
            "loyalty",
            "protection",
            "stability",
            "subtlety",
            "sympathy",
            "wisdom",
        ],
    },
    {
        name: "Ace of Wands",
        words: [
            "adventure",
            "beginning",
            "creative urge",
            "creativity",
            "energy",
            "enterprise",
            "inspiration",
            "intellect",
            "originality",
            "phallus",
            "potency",
            "potential",
            "strength",
            "vision",
        ],
    },
    {
        name: "2 of Wands",
        words: [
            "ambition",
            "appetite",
            "arrogance",
            "balance",
            "curiosity",
            "decision",
            "design",
            "desire",
            "drive",
            "duality",
            "energy",
            "enthusiasm",
            "expectation",
            "force",
            "lust",
            "plan",
            "progress",
            "project",
            "restlessness",
            "risk",
            "search",
            "thirst",
            "yearning",
        ],
    },
    {
        name: "3 of Wands",
        words: [
            "action",
            "anticipation",
            "assistance",
            "attention",
            "business",
            "care",
            "community",
            "concept",
            "contemplation",
            "creativity",
            "effort",
            "expansion",
            "exploration",
            "flux",
            "foresight",
            "help",
            "hope",
            "motion",
            "observation",
            "outcome",
            "patience",
            "preparation",
            "trade",
            "wait",
        ],
    },
    {
        name: "4 of Wands",
        words: [
            "achievement",
            "blessing",
            "celebration",
            "domestic bliss",
            "expansion",
            "freedom",
            "harmony",
            "joy",
            "outcome",
            "peace",
            "possession",
            "prosperity",
            "serenity",
            "stability",
        ],
    },
    {
        name: "5 of Wands",
        words: [
            "action",
            "adversity",
            "challenge",
            "change",
            "chaos",
            "competition",
            "energy",
            "game",
            "imitation",
            "restriction",
            "rivalry",
            "strife",
            "struggle",
            "training",
        ],
    },
    {
        name: "6 of Wands",
        words: [
            "accomplishment",
            "announcement",
            "arrival",
            "award",
            "balance",
            "fame",
            "growth",
            "harmony",
            "illumination",
            "journey",
            "message",
            "parade",
            "publicity",
            "success",
            "triumph",
        ],
    },
    {
        name: "7 of Wands",
        words: [
            "challenge",
            "competition",
            "creativity",
            "defense",
            "faith",
            "inspiration",
            "negotiation",
            "nonconformity",
            "opinion",
            "opposition",
            "perseverance",
            "self-confidence",
            "struggle",
            "willpower",
        ],
    },
    {
        name: "8 of Wands",
        words: [
            "alliance",
            "announcement",
            "change",
            "climax",
            "decision",
            "logic",
            "message",
            "movement",
            "option",
            "progress",
            "reaction",
            "speed",
            "strength",
            "travel",
        ],
    },
    {
        name: "9 of Wands",
        words: [
            "adventure",
            "arrival",
            "defense",
            "experience",
            "fruition",
            "fulfillment",
            "guard",
            "integration",
            "obstacle",
            "opposition",
            "potential",
            "rationality",
            "resilience",
            "risk",
            "strength",
            "threshold",
            "transformation",
            "vigilance",
            "work",
        ],
    },
    {
        name: "10 of Wands",
        words: [
            "burden",
            "completion",
            "culmination",
            "ending",
            "exhaustion",
            "manifestation",
            "overwhelming",
            "strength",
            "work",
        ],
    },
    {
        name: "Page of Wands",
        words: [
            "candid",
            "commitment",
            "creativity",
            "enthusiasm",
            "friendship",
            "impetuous",
            "insight",
            "love",
            "loyalty",
            "play",
            "support",
            "travel",
            "vitality",
        ],
    },
    {
        name: "Knight of Wands",
        words: [
            "action",
            "adventure",
            "capability",
            "chivalry",
            "courage",
            "determination",
            "enterprise",
            "exploration",
            "foresight",
            "formation",
            "idealism",
            "impatience",
            "impetuous",
            "intellect",
            "opportunity",
            "optimism",
            "passion",
            "travel",
        ],
    },
    {
        name: "Queen of Wands",
        words: [
            "autonomy",
            "concept",
            "dignity",
            "dominance",
            "exuberance",
            "influence",
            "passion",
            "power",
            "satisfaction",
            "self-confidence",
        ],
    },
    {
        name: "King of Wands",
        words: [
            "authority",
            "bold",
            "boss",
            "courage",
            "creative urge",
            "dominance",
            "entrepreneur",
            "experience",
            "explosion",
            "initiative",
            "inspiration",
            "motivator",
            "persuasive",
            "respect",
            "security",
            "stability",
            "vision",
        ],
    },
    {
        name: "Fool reversed",
        words: ["ending", "enlightenment", "experience"],
    },
    {
        name: "Magician reversed",
        words: [
            "complacency",
            "loss of control",
            "passivity",
            "unconscious mind",
            "yin",
        ],
    },
    {
        name: "High Priestess reversed",
        words: ["action", "conscious mind", "yang"],
    },
    {
        name: "Empress reversed",
        words: ["masculinity", "pain", "paternity"],
    },
    {
        name: "Emperor reversed",
        words: [
            "femininity",
            "inexperience",
            "irrationality",
            "irresponsibility",
            "maternity",
        ],
    },
    {
        name: "Hierophant reversed",
        words: ["loss of faith"],
    },
    {
        name: "Lovers reversed",
        words: ["pain", "solitude"],
    },
    {
        name: "Chariot reversed",
        words: ["defeat", "fear", "loss of control", "nonphysical conquest"],
    },
    {
        name: "Strength reversed",
        words: ["fear", "physical conquest", "weakness"],
    },
    {
        name: "Hermit reversed",
        words: ["ignorance", "relationship"],
    },
    {
        name: "Wheel of Fortune reversed",
        words: [],
    },
    {
        name: "Justice reversed",
        words: [
            "chaos",
            "indecision",
            "irrationality",
            "irresponsibility",
            "unfairness",
        ],
    },
    {
        name: "Hanged Man reversed",
        words: ["expansion"],
    },
    {
        name: "Death reversed",
        words: ["beginning", "gain"],
    },
    {
        name: "Temperance reversed",
        words: ["chaos", "weakness"],
    },
    {
        name: "Devil reversed",
        words: [
            "belief",
            "control",
            "enlightenment",
            "faith",
            "generosity",
            "health",
            "hope",
            "strength",
        ],
    },
    {
        name: "Tower reversed",
        words: ["balance", "peace", "serenity"],
    },
    {
        name: "Star reversed",
        words: [
            "chaos",
            "drama",
            "hopelessness",
            "loss of faith",
            "selfishness",
            "struggle",
        ],
    },
    {
        name: "Moon reversed",
        words: ["bravery", "conscious mind", "nightmare"],
    },
    {
        name: "Sun reversed",
        words: [
            "cold",
            "dissatisfaction",
            "failure",
            "ignorance",
            "sadness",
            "selfishness",
        ],
    },
    {
        name: "Judgment reversed",
        words: [],
    },
    {
        name: "World reversed",
        words: ["beginning", "failure", "ignorance"],
    },
    {
        name: "Ace of Pentacles reversed",
        words: ["ending", "failure", "loss"],
    },
    {
        name: "2 of Pentacles reversed",
        words: ["chaos", "dissatisfaction", "indecision"],
    },
    {
        name: "3 of Pentacles reversed",
        words: ["laziness"],
    },
    {
        name: "4 of Pentacles reversed",
        words: [
            "generosity",
            "loss",
            "loss of control",
            "restriction",
            "waste",
        ],
    },
    {
        name: "5 of Pentacles reversed",
        words: [
            "expansion",
            "gain",
            "happiness",
            "peace",
            "serenity",
            "thrift",
            "warmth",
        ],
    },
    {
        name: "6 of Pentacles reversed",
        words: ["chaos", "failure", "loss", "selfishness", "unfairness"],
    },
    {
        name: "7 of Pentacles reversed",
        words: ["failure", "loss of faith", "restriction"],
    },
    {
        name: "8 of Pentacles reversed",
        words: ["weakness"],
    },
    {
        name: "9 of Pentacles reversed",
        words: ["dissatisfaction", "failure"],
    },
    {
        name: "10 of Pentacles reversed",
        words: ["beginning"],
    },
    {
        name: "Page of Pentacles reversed",
        words: ["weakness"],
    },
    {
        name: "Knight of Pentacles reversed",
        words: [
            "complacency",
            "passivity",
            "rationality",
            "responsibility",
            "yin",
        ],
    },
    {
        name: "Queen of Pentacles reversed",
        words: ["cold", "irrationality", "paternity", "selfishness"],
    },
    {
        name: "King of Pentacles reversed",
        words: ["failure", "irrationality"],
    },
    {
        name: "Ace of Swords reversed",
        words: ["ending", "failure", "irresponsibility"],
    },
    {
        name: "2 of Swords reversed",
        words: ["chaos", "indecision"],
    },
    {
        name: "3 of Swords reversed",
        words: ["happiness", "pleasure"],
    },
    {
        name: "4 of Swords reversed",
        words: [
            "chaos",
            "drama",
            "relationship",
            "restriction",
            "sleeplessness",
            "struggle",
        ],
    },
    {
        name: "5 of Swords reversed",
        words: [
            "accomplishment",
            "expansion",
            "fairness",
            "happiness",
            "health",
            "justice",
            "peace",
            "strength",
            "success",
            "victory",
        ],
    },
    {
        name: "6 of Swords reversed",
        words: ["chaos"],
    },
    {
        name: "7 of Swords reversed",
        words: ["gain", "loss of faith", "victory"],
    },
    {
        name: "8 of Swords reversed",
        words: ["expansion", "weakness", "work"],
    },
    {
        name: "9 of Swords reversed",
        words: ["dream", "gain", "happiness", "sleep"],
    },
    {
        name: "10 of Swords reversed",
        words: [
            "accomplishment",
            "beginning",
            "bravery",
            "happiness",
            "pleasure",
            "success",
            "victory",
        ],
    },
    {
        name: "Page of Swords reversed",
        words: [],
    },
    {
        name: "Knight of Swords reversed",
        words: ["complacency", "passivity", "yin"],
    },
    {
        name: "Queen of Swords reversed",
        words: ["indecision", "weakness"],
    },
    {
        name: "King of Swords reversed",
        words: ["irrationality", "unfairness"],
    },
    {
        name: "Ace of Cups reversed",
        words: ["conscious mind", "dissatisfaction", "ending"],
    },
    {
        name: "2 of Cups reversed",
        words: ["chaos", "dissatisfaction", "indecision", "solitude"],
    },
    {
        name: "3 of Cups reversed",
        words: ["defeat", "dissatisfaction", "laziness", "weakness"],
    },
    {
        name: "4 of Cups reversed",
        words: ["action", "joy", "restriction"],
    },
    {
        name: "5 of Cups reversed",
        words: ["bravery", "expansion", "happiness", "optimism"],
    },
    {
        name: "6 of Cups reversed",
        words: ["chaos", "dissatisfaction", "drama", "struggle"],
    },
    {
        name: "7 of Cups reversed",
        words: ["decision", "loss of faith", "nightmare"],
    },
    {
        name: "8 of Cups reversed",
        words: ["weakness"],
    },
    {
        name: "9 of Cups reversed",
        words: ["failure", "pain"],
    },
    {
        name: "10 of Cups reversed",
        words: [
            "beginning",
            "chaos",
            "dissatisfaction",
            "drama",
            "failure",
            "sadness",
            "struggle",
        ],
    },
    {
        name: "Page of Cups reversed",
        words: ["dissatisfaction"],
    },
    {
        name: "Knight of Cups reversed",
        words: ["cold", "complacency", "pain", "passivity", "yin"],
    },
    {
        name: "Queen of Cups reversed",
        words: ["cold"],
    },
    {
        name: "King of Cups reversed",
        words: ["dissatisfaction"],
    },
    {
        name: "Ace of Wands reversed",
        words: ["ending", "weakness"],
    },
    {
        name: "2 of Wands reversed",
        words: ["chaos", "indecision"],
    },
    {
        name: "3 of Wands reversed",
        words: [
            "complacency",
            "hopelessness",
            "passivity",
            "restriction",
            "yin",
        ],
    },
    {
        name: "4 of Wands reversed",
        words: ["chaos", "dissatisfaction", "drama", "restriction", "struggle"],
    },
    {
        name: "5 of Wands reversed",
        words: [
            "balance",
            "complacency",
            "expansion",
            "passivity",
            "peace",
            "serenity",
            "yin",
        ],
    },
    {
        name: "6 of Wands reversed",
        words: ["chaos", "failure"],
    },
    {
        name: "7 of Wands reversed",
        words: ["loss of faith", "peace", "serenity"],
    },
    {
        name: "8 of Wands reversed",
        words: ["indecision", "weakness"],
    },
    {
        name: "9 of Wands reversed",
        words: ["inexperience", "irrationality", "laziness", "weakness"],
    },
    {
        name: "10 of Wands reversed",
        words: ["beginning", "laziness", "weakness"],
    },
    {
        name: "Page of Wands reversed",
        words: [],
    },
    {
        name: "Knight of Wands reversed",
        words: ["complacency", "passivity", "pessimism", "yin"],
    },
    {
        name: "Queen of Wands reversed",
        words: [],
    },
    {
        name: "King of Wands reversed",
        words: ["inexperience"],
    },
];

const getCardObjectFromName = (cardName) =>
    cards.find((card) => card.name === cardName);

const getCardObjectsFromNames = (cardNames) =>
    cardNames.map((cardName) => getCardObjectFromName(cardName));

export default cards;
export { getCardObjectsFromNames };
